### ISSUE TITLE
Changing assigns inside form_for resets input values

### ISSUE THREAD

**Issue by grych** [grych/drab#42]
Reported by Eirik Anfinsen by email:

An issue with a changing csfr-token and reset of input fields on poke. Here's some sample code that you could use to recreate and debug:

Controller:

```elixir
  def drab_example(conn, _params) do
    render conn, "drab_example.html", list: ["From controller", "Also from controller"]
  end
```

Template (drab_example.html.drab):

```html
  <h1>Sample form</h1>
  <%= form_for @conn, page_path(@conn, :drab_example), [as: :drab], fn f -> %>
    <%= text_input f, :text, placeholder: "Reset after poke" %>
    <br /><br />
    <%= text_input f, :new_item, placeholder: "Random list item" %>
    <button type="button" drab-click="add_item">Add</button>
    <h2>List</h2>
    <ul>
      <%= for(item <- @list) do %>
        <li><%= item %></li>
      <% end %>
    </ul>
    <%= submit "Submit" %>
  <% end %>
```

Commander: 

```elixir
  def add_item(socket, sender) do
    items = socket |> peek(:list)
    new_item = socket |> Drab.Query.select(:val, from: "#drab_new_item")
    new_list = items ++ ["#{new_item}"]
    Drab.Live.poke socket, list: new_list
  end
```

As you (hopefully!) can see, peek/poke does its job, but when the ul-list is updated on poke, whatever you typed into the first text input is reset to the placeholder text.

What the example does not show, however, is that the form does not pass validation on submit when the protect_from_forgery plug is used. As far as we can tell, this reason for this is thatthe csfr-token generated on page load is changed after the poke.

**Comment by grych** [comment]
### Analysis

In the template there are two functions(macros) which uses assign:
`form_for` (`@conn` and `@list` - notice that `@list` is also inside it)
`for` (`@list`)

That means, when you poke the `@list`, both of the functions are re-evaluated, so everything in the form inputs is replaced with the default. The same is about the csfr token.

Workaround for now: do not use form_for, sorry :( but create form by hand, `<form></form>`

I have no idea (yet) how to solve it. I even don’t know if it is solvable, because this behaviour is a Drab’s core. Maybe I will need to add it to the limitations list.

**Comment by OvermindDL1** [comment]
You could always replace form_for with your own version?

**Comment by grych** [comment]
Unfortunatelly, not so easy. It affects any `<input>` which is inside the expression, it doesn't have to be `form_for`.

```html
<%= if (something) do %>
  <%= @some_assign %>
  <input>
<% end %>
```

Updating `@some_assign` with `poke` will re-render the whole `if` expression (as this assign is inside that expression). So anything user put in the `<input>` will disapear.

**Comment by OvermindDL1** [comment]
Hmm, I really need to try Drab.Live in my setup.  Just about everything is inside (usually multiple layers of) `if`/`for`/`case` and more...

**Comment by grych** [comment]
`<input>` values must survive refreshing the parent expression. Otherwise it is counter-intuitive. Drab.Live should be a black magic: things should just happen.

**Comment by OvermindDL1** [comment]
Sounds almost like you need to make a virtual dom and 'patch' it onto the main instead of swapping.  ^.^

Hmm, now that would be an interesting idea...  A Drab.VDom library...

**Comment by eirikra** [comment]
If I'm not mistaken, we found that another workaround (if you don't want to build the form manually) is to not use the :protect_from_forgery plug. This might, however, not be something you'd necessarilty want to do...

**Comment by grych** [comment]
@eirikra but it still resets the values of <input>, doesn't it?

**Comment by eirikra** [comment]
Ah, my apologies. I confused two different issues. I need to double check this, however, but – if I remember correctly – when using protect from forgery forms are not validated because the csfr-token is changed after poke.

**Comment by grych** [comment]
Actually, it is not very complicated to fix.
Before update, I am going to collect all values on `<input>` fields, by `name` attribute. After the update, I will fill up the corresponding values with the saved ones. 
This should fix the csrf issue as well, as it is stored in the `hidden` input.

**Comment by denisw** [comment]
But won't you still have the problem that the re-rendered inputs possibly lose focus / the cursor position? It's impossible to completely restore an input's state after replacing it.

These are the kinds of re-rendering provlems that drove me crazy when I was still using Backbone.js :)

It seems that the only real solution here is using a virtual DOM implementation (there are wuite a few out there not bound to a framework), or very exact data binding.

**Comment by OvermindDL1** [comment]
> It seems that the only real solution here is using a virtual DOM implementation (there are wuite a few out there not bound to a framework), or very exact data binding.

Technically Drab Live's special EEX handler is making a kind of virtual DOM.  :-)

**Comment by grych** [comment]
Yes, there is a kind of virtual DOM there, under heavy rebuild now.

The root of the issue is how Drab searches for assigns in the expression. Compiled template like:

```html
<%= if true do %>
  <%= @assign %>
<% end %>
```

contains two expressions (`if` and `assign`), and both of them contain this assign. When `poking` the `@assign`, drab re-renders both of them, because it is too stupid to recognize that it should be only done in the second one.

One of solutions would be to allow developer to to choose where *not to drab* the expression with the custom marker:

```html
<%/ if true do %>
  <%= @assign %>
<% end %>
```

For this, I made this PR elixir-lang/elixir/pull/6281. But it is not enough, it should be more clever choosing where to eval and replace the expressions.

**Comment by OvermindDL1** [comment]
> it should be more clever choosing where to eval and replace expressions.

Such as by threading an environment through the calls to state what is required and what is not and so forth?

**Comment by grych** [comment]
@eirikra 
could you please test again with current master? I hope I solved the issue.

**Comment by grych** [comment]
Fixed in v0.6.0-pre.1
